name: ci

on:
  workflow_dispatch:
  push:

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: taknok/boinc:latest
          file: Dockerfile

  alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: taknok/boinc:alpine-edge
          file: Dockerfile.alpine

  AMD:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: taknok/boinc:amd-latest
          file: Dockerfile.amd

  intel:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: taknok/boinc:intel-latest
          file: Dockerfile.intel

  nvidia:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: taknok/boinc:nvidia-latest
          file: Dockerfile.nvidia

  multi-gpu:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: taknok/boinc:multi-gpu-latest
          file: Dockerfile.multi-gpu
